myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('trail/',views.trail,name="Trail"),
    path('profile/',views.profile,name="profile"),
    path('get_demo/',views.get_demo,name="get_demo"),
    path('post_demo/',views.post_demo,name="post_demo"),
    path('register/',views.register,name="register"),
    path('multiselect/',views.multiselect,name="multiselect"),
    path('img/',views.img_upld,name="img"),
    path('img_display/',views.img_display,name="img_display"),
    path('builtin/',views.builtinforms,name="builtinforms"),
]

p13/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/forms.py
from django import forms
choices_year=[('1947', '1947'), ('1948', '1948'), ('1949', '1949'), ('1950', '1950'), ('1951', '1951'), ('1952', '1952'), ('1953', '1953'), ('1954', '1954'), ('1955', '1955'), ('1956', '1956'), ('1957', '1957'), ('1958', '1958'), ('1959', '1959'), ('1960', '1960'), ('1961', '1961'), ('1962', '1962'), ('1963', '1963'), ('1964', '1964'), ('1965', '1965'), ('1966', '1966'), ('1967', '1967'), ('1968', '1968'), ('1969', '1969'), ('1970', '1970'), ('1971', '1971'), ('1972', '1972'), ('1973', '1973'), ('1974', '1974'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')]
choices_month=[('1','jan'),('2','feb'),('3','mar'),('4','Apr'),('5','may')]
choices_day=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')]
class SampleForm(forms.Form):
    first_name= forms.CharField(max_length=20,required=True,label="First Name",help_text="spaces and special characters are not allowed")
    last_name= forms.CharField(max_length=20,required=True,label="Last Name")
    email= forms.EmailField(max_length=20,required=True,label="Email")
    phone= forms.IntegerField(max_value=9999999999,min_value=6000000000,required=True,help_text="No country codes")
    pwd= forms.CharField(max_length=20,required=True,widget=forms.PasswordInput,label="Password")
    birth_day= forms.ChoiceField(choices=choices_day,required=True,label="birth_day")
    birth_month= forms.ChoiceField(choices=choices_month,required=True,label="birth_month")
    birth_year= forms.ChoiceField(choices=choices_year,required=True,label="birth_year")
    gender= forms.ChoiceField(choices=[('male','male'),('Female','Female')],widget=forms.RadioSelect)

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.core.mail import send_mail
from myapp import forms

# Create your views here.
def trail(request):
    return HttpResponse("<h1>project is on air</h1>")

def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"myapp/home.html")    

def profile(request):
    name="sachin"
    return render(request,"myapp/profile.html",{'name':name})

def get_demo(request):
    name=request.GET.get('name')
    return render(request,"get_demo.html",{'name':name})

def post_demo(request):
    if request.method=="POST":
        name=request.POST.get('name')
        return HttpResponse("<h1>Thanks for submission Mr./Ms. {}</h1>".format(name))
    return render(request,"post_demo.html") 

def register(request):
    if request.method=="POST":
        first_name=request.POST.get("first_name")
        second_name=request.POST.get("second_name")
        email=request.POST.get("email")
        password=request.POST.get("pwd")
        phno=request.POST.get("phno")
        date=request.POST.get("birthday_day")
        month=request.POST.get("birthday_month")
        year=request.POST.get("birthday_year")
        gender=request.POST.get("sex")
        if gender=="1":
            gender="Female"
        else:
            gender="Male"

        send_mail("Thanks for Registration","hello Mr./Ms.{} {}\n Thanks for Registering".format(first_name,second_name),
        "sachinkn2019@gmail.com" ,[email,],fail_silently=True)
        return redirect("home")
    return render(request,"myapp/register.html")


def multiselect(request):
    if request.method=="POST":
        foods=request.POST.getlist("food")
        languages=request.POST.getlist("language")
        return HttpResponse("<h1>{}{}<h1>".format(foods,languages))
    return render(request,'multiselect.html')

from django.core.files.storage import FileSystemStorage

def img_upld(request):
    return render(request,"img_upld.html")

from myapp.utilities import store_image

def img_display(request):
    file_url=False
    if request.method=="POST" and request.FILES:
        image1=request.FILES.get('sam1')
        image2=request.FILES.get('sam2')
        file_urls=map(store_image,[image1,image2])

    return render(request,"img_display.html",context={'file_urls':file_urls})


def builtinforms(request):
    form=forms.SampleForm()
    return render(request,'builtinform.html',{'form':form})

    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Base page</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


</head>
<body>
    {% include "partials/_topbar.html" %}
    {% include "partials/_navbar.html" %}
    
      {% block content %}
         <div class="container">
             <div class="jumbotron">
                 <h1>welcome to base page</h1>
                 <img src="{% static 'images/sacimage.jpg' %}" alt="No image found" height="100" width="100">
             </div>
        </div>
    {% endblock %}
    
    {% include "partials/_footer.html" %}
    
</body>
</html>

templates/builtinform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Builtin Form</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <!--{{form.as_p}}-->
        <!--<table border="2px">
            {{form.as_table}}
        </table>-->
        <ul>
            {{form.as_ul}}
        </ul>
        <input type="submit" values="SUBMIT">            
    </form>
</body>
</html>

templates/get_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GET demo</title>
</head>
<body>
    <form method="GET">
        <label for="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="submit">
    </form>
    <h1>{{name}}</h1>
    
</body>
</html>

templates/img_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>image display</title>
</head>
<body>
    {% for file_url in file_urls %}
    {% if file_url %}
       <img src="{{ file_url }}" alt="No Image Found" height="600" width="400">
    {% endif %}
    {% endfor %}   
</body>
</html>

templates/img_upld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>image upload</title>
</head>
<body>
    <form action="{% url 'myapp:img_display' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        Image1:<input type="file" name="sam1" id="sam1"><br>
        Image2:<input type="file" name="sam2" id="sam2">
        <input type="submit" value="submit">
    </form>
      
</body>
</html>

templates/multiselect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>multiselect and checkboxes</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="languages">choose your language:</label>
        <select name="language" id="languages" multiple>
            <option value="python">python</option>
            <option value="c++">c++</option>
            <option value="c">c</option>
            <option value="asp.net">asp.net</option>
            <option value="php">php</option>
            <option value="sap">sap</option>
            <option value="datascience">datascience</option>
        </select><br>
        <h6>choose your food</h6>
        <label for="idli">
            Idli
        </label>
        <input type="checkbox" name="food" id="idli" value="Idli">
        <label for="vada">
            vada
        </label>
        <input type="checkbox" name="food" id="vada" value="vada">
        <label for="chiken65">
            chiken65
        </label>
        <input type="checkbox" name="food" id="chiken65" value="chiken65">
        <label for="pepperrice">
            pepperrice
        </label>
        <input type="checkbox" name="food" id="pepperrice" value="pepperrice">
        <label for="fish kabab">
            fish kabab
        </label>
        <input type="checkbox" name="food" id="fish kabab" value="fish kabab">
        <input type="submit" value="submit">
    </form>
</body>
</html>

templates/myapp/home.html
{% extends "base.html" %}

{% block title %}
    <title>home page</title>
{% endblock %}

{% block content %}
       <div class="container">
           <div class="jumbtron">
               <h1>welcome to home page</h1>
           </div>
       </div>
{% endblock %}       

templates/myapp/profile.html
{% extends "base.html" %}

{% block title %}
    <title>profile page</title>
{% endblock %}

{% block content %}
       <div class="container">
           <div class="jumbtron">
               <h1>welcome to {{name}} profile page</h1>
           </div>
       </div>
{% endblock %}       

templates/partials/_footer.html
<!--footer-->
<div class="alert alert-primary" role="alert">
    <center>Footer</center>
</div>

templates/partials/_navbar.html
<!--navbar-->
<div class="container">
    <ul class="nav">
        <li class="nav-item">
           <a class="nav-link active" href="{% url 'home' %}">home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:profile' %}">profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:register' %}">register</a>
        </li>
    </ul>

</div>

templates/partials/_topbar.html
<!--topbar-->
<div class="alert alert-primary" role="alert">
    <center>Top Bar</center>
</div>

templates/post_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post demo</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="submit">        
    </form>
</body>
</html>